/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: internal/sat.i

#ifndef SWIG_internal_WRAP_H_
#define SWIG_internal_WRAP_H_

class Swig_memory;

class SwigDirector_SolutionCallback : public operations_research::sat::SolutionCallback
{
 public:
  SwigDirector_SolutionCallback(int swig_p);
  virtual ~SwigDirector_SolutionCallback();
  virtual void OnSolutionCallback() const;
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

class SwigDirector_LogCallback : public operations_research::sat::LogCallback
{
 public:
  SwigDirector_LogCallback(int swig_p);
  virtual ~SwigDirector_LogCallback();
  virtual void NewMessage(std::string const &message);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
